// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPl13dRXwnlJo8br-2-rI9jkLswRh8kc',
    appId: '1:492141880534:android:b7ad93a6259acc8d81d577',
    messagingSenderId: '492141880534',
    projectId: 'icare-1931f',
    storageBucket: 'icare-1931f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiIb350E58kE0ksXurFusD18dKB2Ykx_8',
    appId: '1:492141880534:ios:90dbee0aae2fa97181d577',
    messagingSenderId: '492141880534',
    projectId: 'icare-1931f',
    storageBucket: 'icare-1931f.appspot.com',
    androidClientId: '492141880534-l7u7fgq2bknrj7cg2ss6lgqbqqlp013c.apps.googleusercontent.com',
    iosClientId: '492141880534-f2dvgintrm0kjqe1aa7b67dkq1hju38m.apps.googleusercontent.com',
    iosBundleId: 'com.example.icareMobile',
  );
}
